framework:
    validation:
        mapping:
            paths:
                - '%kernel.project_dir%/config/packages/validator/arrendatario.yaml'


when@test:
    framework:
        validation:
            not_compromised_password: false
